// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import (
	. "github.com/JubaerHossain/gomd/gomd"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)


func DocRegister() {
	// programmatically set swagger info
	SwaggerInfo.Title = "Swagger Example API"
	SwaggerInfo.Description = "This is a sample server Petstore server."
	SwaggerInfo.Version = "1.0"
	SwaggerInfo.Host = "petstore.swagger.io"
	SwaggerInfo.BasePath = "/v2"
	SwaggerInfo.Schemes = []string{"http", "https"}

	// use ginSwagger middleware to serve the API docs
	Router.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

}


